services:
  consul:
    image: consul:1.14
    platform: linux/amd64   # <-- esta línea fuerza la arquitectura correcta
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: ["agent", "-server", "-bootstrap", "-ui", "-client=0.0.0.0"]
    networks:
      - consul-net

networks:
  consul-net:
    driver: bridge
